//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TDSClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        public static string lblX {
            get {
                return ResourceManager.GetString("lblX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        public static string lblY {
            get {
                return ResourceManager.GetString("lblY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string strActivites {
            get {
                return ResourceManager.GetString("strActivites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string strActivity {
            get {
                return ResourceManager.GetString("strActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure You Want to Delete It?.
        /// </summary>
        public static string strAreyousureyouwanttodeleteit {
            get {
                return ResourceManager.GetString("strAreyousureyouwanttodeleteit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string strbtnCancel {
            get {
                return ResourceManager.GetString("strbtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string strbtnClear {
            get {
                return ResourceManager.GetString("strbtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string strbtnDelete {
            get {
                return ResourceManager.GetString("strbtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string strbtnEdit {
            get {
                return ResourceManager.GetString("strbtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string strbtnExit {
            get {
                return ResourceManager.GetString("strbtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string strbtnFind {
            get {
                return ResourceManager.GetString("strbtnFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string strbtnInsert {
            get {
                return ResourceManager.GetString("strbtnInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string strbtnNew {
            get {
                return ResourceManager.GetString("strbtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string strbtnOK {
            get {
                return ResourceManager.GetString("strbtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string strbtnSelect {
            get {
                return ResourceManager.GetString("strbtnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate.
        /// </summary>
        public static string strCoordinate {
            get {
                return ResourceManager.GetString("strCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string strDelete {
            get {
                return ResourceManager.GetString("strDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string strDuration {
            get {
                return ResourceManager.GetString("strDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Activity.
        /// </summary>
        public static string strEndActivity {
            get {
                return ResourceManager.GetString("strEndActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed (Kmh).
        /// </summary>
        public static string strGridHeaderSpeedKmh {
            get {
                return ResourceManager.GetString("strGridHeaderSpeedKmh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Level Road.
        /// </summary>
        public static string strHighLevelRoad {
            get {
                return ResourceManager.GetString("strHighLevelRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate points.
        /// </summary>
        public static string strIntermediatepoints {
            get {
                return ResourceManager.GetString("strIntermediatepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Level Road.
        /// </summary>
        public static string strLowLevelRoad {
            get {
                return ResourceManager.GetString("strLowLevelRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark On The Map.
        /// </summary>
        public static string strMarkOnTheMap {
            get {
                return ResourceManager.GetString("strMarkOnTheMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string strMax {
            get {
                return ResourceManager.GetString("strMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Level Road.
        /// </summary>
        public static string strMediumLevelRoad {
            get {
                return ResourceManager.GetString("strMediumLevelRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string strMove {
            get {
                return ResourceManager.GetString("strMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string strNameColon {
            get {
                return ResourceManager.GetString("strNameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string strPlatform {
            get {
                return ResourceManager.GetString("strPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Name.
        /// </summary>
        public static string strPlatformName {
            get {
                return ResourceManager.GetString("strPlatformName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Name is Empty.
        /// </summary>
        public static string strPlatformNameisEmpty {
            get {
                return ResourceManager.GetString("strPlatformNameisEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platforms.
        /// </summary>
        public static string strPlatforms {
            get {
                return ResourceManager.GetString("strPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform With The Same Name Already Exists.
        /// </summary>
        public static string strPlatformWithTheSamenameAlreadyExists {
            get {
                return ResourceManager.GetString("strPlatformWithTheSamenameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Point.
        /// </summary>
        public static string strReferencePoint {
            get {
                return ResourceManager.GetString("strReferencePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Point Must be Filled.
        /// </summary>
        public static string strReferencePointMustbeFilled {
            get {
                return ResourceManager.GetString("strReferencePointMustbeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Planning.
        /// </summary>
        public static string strRoadPlanning {
            get {
                return ResourceManager.GetString("strRoadPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roads Filter.
        /// </summary>
        public static string strRoadsFilter {
            get {
                return ResourceManager.GetString("strRoadsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string strRoute {
            get {
                return ResourceManager.GetString("strRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Name.
        /// </summary>
        public static string strRouteName {
            get {
                return ResourceManager.GetString("strRouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Name Already Exist.
        /// </summary>
        public static string strRouteNameAlreadyExist {
            get {
                return ResourceManager.GetString("strRouteNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Name is Empty.
        /// </summary>
        public static string strRouteNameisEmpty {
            get {
                return ResourceManager.GetString("strRouteNameisEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Poins Must be Added.
        /// </summary>
        public static string strRoutePoinsmustbeadded {
            get {
                return ResourceManager.GetString("strRoutePoinsmustbeadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string strRoutes {
            get {
                return ResourceManager.GetString("strRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Exit.
        /// </summary>
        public static string strSaveAndExit {
            get {
                return ResourceManager.GetString("strSaveAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Me.
        /// </summary>
        public static string strShowMe {
            get {
                return ResourceManager.GetString("strShowMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Point.
        /// </summary>
        public static string strSourcePoint {
            get {
                return ResourceManager.GetString("strSourcePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Activity.
        /// </summary>
        public static string strStartActivity {
            get {
                return ResourceManager.GetString("strStartActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Point.
        /// </summary>
        public static string strTargetPoint {
            get {
                return ResourceManager.GetString("strTargetPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string strToolTipSearch {
            get {
                return ResourceManager.GetString("strToolTipSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeploy.
        /// </summary>
        public static string strUndeploy {
            get {
                return ResourceManager.GetString("strUndeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Construction.
        /// </summary>
        public static string strUnderConstruction {
            get {
                return ResourceManager.GetString("strUnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string strZoom {
            get {
                return ResourceManager.GetString("strZoom", resourceCulture);
            }
        }
    }
}
